# -*- coding: utf-8 -*-
codes = {
    'ab': 'Abkhazian',
    'ace': 'Acehnese',
    'af': 'Afrikaans',
    'ak': 'Akan',
    'als': 'Alemannic',
    'am': 'Amharic',
    'an': 'Aragonese',
    'ang': 'Anglo-Saxon',
    'ar': 'Arabic',
    'arc': 'Aramaic',
    'arz': 'Egyptian Arabic',
    'as': 'Assamese',
    'ast': 'Asturian',
    'av': 'Avar',
    'ay': 'Aymara',
    'az': 'Azerbaijani',
    'azb': 'Southern Azerbaijani',
    'ba': 'Bashkir',
    'bar': 'Bavarian',
    'bat-smg': 'Samogitian',
    'bcl': 'Central Bicolano',
    'be': 'Belarusian',
    'be-x-old': 'Belarusian (Taraškievica)',
    'bg': 'Bulgarian',
    'bh': 'Bihari',
    'bi': 'Bislama',
    'bjn': 'Banjar',
    'bm': 'Bambara',
    'bn': 'Bengali',
    'bo': 'Tibetan',
    ' bpy': 'Bishnupriya Manipuri',
    'br': 'Breton',
    'bs': 'Bosnian',
    'bug': 'Buginese',
    'bxr': 'Buryat',
    'ca': 'Catalan',
    'cbk-zam': 'Chavacano',
    'cdo': 'Min Dong',
    'ce': 'Chechen',
    'ceb': 'Cebuano',
    'ch': 'Chamorro',
    'chr': 'Cherokee',
    'chy': 'Cheyenne',
    'ckb': 'Sorani',
    'co': 'Corsican',
    'cr': 'Cree',
    'Tatar': 'Crimean',
    'cs': 'Czech',
    'csb': 'Kashubian',
    'cu': 'Old Church Slavonic',
    'cv': 'Chuvash',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'diq': 'Zazaki',
    'dsb': 'Sorbian Lower',
    'dv': 'Divehi',
    'dz': 'Dzongkha',
    'ee': 'Ewe',
    'el': 'Greek',
    'eml': 'Emilian-Romagnol',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'ext': 'Extremaduran',
    'fa': 'Persian',
    'ff': 'Fula',
    'fi': 'Finnish',
    'fiu-vro': 'Võro',
    'fj': 'Fijian',
    'fo': 'Faroese',
    'fr': 'French',
    'frp': 'Franco-Provençal',
    'frr': 'North Frisian',
    'fur': 'Friulian',
    'fy': 'West Frisian',
    'ga': 'Irish',
    'gag': 'Gagauz',
    'gan': 'Gan',
    'gd': 'Scottish Gaelic',
    'gl': 'Galician',
    'glk': 'Gilaki',
    'gn': 'Guarani',
    'gom': 'Goan Konkani',
    'got': 'Gothic',
    'gu': 'Gujarati',
    'gv': 'Manx',
    'ha': 'Hausa',
    'hak': 'Hakka',
    'haw': 'Hawaiian',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hif': 'Fiji Hindi',
    'hr': 'Croatian',
    'hsb': 'Upper Sorbian',
    'ht': 'Haitian',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'ia': 'Interlingua',
    'id': 'Indonesian',
    'ie': 'Interlingue',
    'ig': 'Igbo',
    'ik': 'Inupiak',
    'ilo': 'Ilokano',
    'io': 'Ido',
    'is': 'Icelandic',
    'it': 'Italian',
    'iu': 'Inuktitut',
    'ja': 'Japanese',
    'jbo': 'Lojban',
    'jv': 'Javanese',
    'ka': 'Georgian',
    'kaa': 'Karakalpak',
    'kab': 'Kabyle',
    'kbd': 'Kabardian',
    'kg': 'Kongo',
    'ki': 'Kikuyu',
    'kk': 'Kazakh',
    'kl': 'Greenlandic',
    'km': 'Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'koi': 'Komi-Permyak',
    'krc': 'Karachay-Balkar',
    'ks': 'Kashmiri',
    'ksh': 'Ripuarian',
    'ku': 'Kurdish',
    'kv': 'Komi',
    'kw': 'Cornish',
    'ky': 'Kirghiz',
    'la': 'Latin',
    'lad': 'Ladino',
    'lb': 'Luxembourgish',
    'lbe': 'Lak',
    'lez': 'Lezgian',
    'lg': 'Luganda',
    'li': 'Limburgish',
    'lij': 'Ligurian',
    'lmo': 'Lombard',
    'ln': 'Lingala',
    'lo': 'Lao',
    'Luri': 'Northern',
    'lt': 'Lithuanian',
    'ltg': 'Latgalian',
    'lv': 'Latvian',
    'mai': 'Maithili',
    'map-bms': 'Banyumasan',
    'mdf': 'Moksha',
    'mg': 'Malagasy',
    'Mari': 'Meadow',
    'mi': 'Maori',
    'min': 'Minangkabau',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn': 'Mongolian',
    'mr': 'Marathi',
    'Mari': 'Hill',
    'ms': 'Malay',
    'mt': 'Maltese',
    'mwl': 'Mirandese',
    'my': 'Burmese',
    'myv': 'Erzya',
    'mzn': 'Mazandarani',
    'na': 'Nauruan',
    'nah': 'Nahuatl',
    'nap': 'Neapolitan',
    'Saxon': 'Low',
    'Low': 'Dutch',
    'ne': 'Nepali',
    'new': 'Newar',
    'nl': 'Dutch',
    'nn': 'Norwegian (Nynorsk)',
    'no': 'Norwegian (Bokmål)',
    'nov': 'Novial',
    'nrm': 'Norman',
    'nso': 'Northern Sotho',
    'nv': 'Navajo',
    'ny': 'Chichewa',
    'oc': 'Occitan',
    'om': 'Oromo',
    'or': 'Oriya',
    'os': 'Ossetian',
    'pa': 'Punjabi',
    'pag': 'Pangasinan',
    'pam': 'Kapampangan',
    'pap': 'Papiamentu',
    'pcd': 'Picard',
    'pdc': 'Pennsylvania German',
    'pfl': 'German Palatinate',
    'pi': 'Pali',
    'pih': 'Norfolk',
    'pl': 'Polish',
    'pms': 'Piedmontese',
    'pnb': 'Western Punjabi',
    'pnt': 'Pontic',
    'ps': 'Pashto',
    'pt': 'Portuguese',
    'qu': 'Quechua',
    'rm': 'Romansh',
    'rmy': 'Romani',
    'rn': 'Kirundi',
    'ro': 'Romanian',
    'roa-rup': 'Aromanian',
    'roa-tara': 'Tarantino',
    'ru': 'Russian',
    'rue': 'Rusyn',
    'rw': 'Kinyarwanda',
    'sa': 'Sanskrit',
    'sah': 'Sakha',
    'sc': 'Sardinian',
    'scn': 'Sicilian',
    'sco': 'Scots',
    'sd': 'Sindhi',
    'Sami': 'Northern',
    'sg': 'Sango',
    'sh': 'Serbo-Croatian',
    'si': 'Sinhalese',
    'simple': 'Simple English',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sm': 'Samoan',
    'sn': 'Shona',
    'so': 'Somali',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'srn': 'Sranan',
    'ss': 'Swati',
    'st': 'Sesotho',
    'stq': 'Saterland Frisian',
    'su': 'Sundanese',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'szl': 'Silesian',
    'ta': 'Tamil',
    'te': 'Telugu',
    'tet': 'Tetum',
    'tg': 'Tajik',
    'th': 'Thai',
    'ti': 'Tigrinya',
    'tk': 'Turkmen',
    'tl': 'Tagalog',
    'tn': 'Tswana',
    'to': 'Tongan',
    'tpi': 'Tok Pisin',
    'tr': 'Turkish',
    'ts': 'Tsonga',
    'tt': 'Tatar',
    'tum': 'Tumbuka',
    'tw': 'Twi',
    'ty': 'Tahitian',
    'tyv': 'Tuvan',
    'udm': 'Udmurt',
    'ug': 'Uyghur',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    've': 'Venda',
    'vec': 'Venetian',
    'vep': 'Vepsian',
    'vi': 'Vietnamese',
    'vls': 'West Flemish',
    'vo': 'Volapük',
    'wa': 'Walloon',
    'war': 'Waray-Waray',
    'wo': 'Wolof',
    'wuu': 'Wu',
    'xal': 'Kalmyk',
    'xh': 'Xhosa',
    'xmf': 'Mingrelian',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'za': 'Zhuang',
    'zea': 'Zeelandic',
    'zh': 'Chinese',
    'zh-classical': 'Classical Chinese',
    'Nan': 'Min',
    'zh-yue': 'Cantonese',
    'zu': 'Zulu'
}
